name: node_version
on:
 push:
  branches:
   - main
jobs:
 node_version:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-node@v4
     with:
      node-version: 21.5.0
   - run: npm ci && npm run build
